version: '3'

services:
  appplication:
    image: lasbau/esp_docker:latest
    restart: always
    container_name: app 
    ports:
      - "3000:3000"
      - "1883:1883"
    links:
      - database
    networks: 
      - backend
    volumes:
      - ./config:/usr/src/app/config
  database:
    build: .
    container_name:  database
    restart: always
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - backend
networks:
  backend:
    driver: "bridge"
volumes:
  dbdata: 